openapi: 3.0.0
info:
  version: '0.1.13'
  title: 'ATS Customer Channel API'
  description: 'Open API Specification for ATS Customer Channel APIs'
  contact:
    email: "avishek.somani@accenture.com"
  license: 
    name: "Accenture Confidential Information"
    url: "http://api.abt.com/v1"

servers:
# Added by API Auto Mocking Plugin
  - url: https://api{vendorID}.presto{environment}.com:{port}/v1/{appType}
    variables:
      vendorID:
        default: pds
        description: "Assigned Vendor ID"
      appType:
        enum:
          - 'cuschannel'
        default: 'cuschannel'
        description: "DeviceType based on device capabilities"
      port:
        enum:
          - '443'
          - '8088'
        default: '8088'
      environment:
        enum:
          - 'build'
          - 'pat'
          - 'iit'
          - 'preprod'
          - 'prod'
        default: 'build'
    description: "API Server"
    
tags:
  - name: "Media"
    description: "This includes all the fare media APIs"
  - name: "Debt"
    description: "This includes all the APIs related to debt recovery"
    
paths:

  /media/configure/profile:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediaconfigureprofile'
  /media/get:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediaget'
  /media/getTransactionHistory:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediagettransactionhistory'
  /media/getLatestUsage:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediagetlatestusage'
  /media/getAssociatedMedia:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediagetassociatedmedia'
  /media/recoverDebt/auto:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediarecoverdebtauto'
  /media/recoverDebt/token:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediarecoverdebttoken'
  /media/recoverDebt/manualInitiate:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediarecoverdebtmanualinitiate'
  /media/recoverDebt/manualResult:
    $ref: 'https://api.swaggerhub.com/domains/ATS-Design/ATSDomain/0.1.13#/components/pathitems/mediarecoverdebtmanualresult'